[project]
name = "stockpicker_agents"
version = "0.1.0"
description = "stockpicker-agents using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.12,<=3.13"
dependencies = [
    "crewai[tools]>=0.86.0,<1.0.0",
    "elasticsearch==8.14.0"
]

[project.scripts]
stockpicker_agents = "stockpicker_agents.main:run"
run_crew = "stockpicker_agents.main:run"
train = "stockpicker_agents.main:train"
replay = "stockpicker_agents.main:replay"
test = "stockpicker_agents.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
