stock_screen:
  description: >
    Scan publicly traded companies for potential buys. 
    Focus on technical (RSI, MACD, SMA) and fundamental triggers. 
    When using the stock_screener tool, apply:
      rsi_day_gte=30, rsi_day_lte=60, macd_week_gt=0, macd_week_lt=10
    Identify the top 10 BUY candidates based on the combined technical and fundamental signals.
  expected_output: >
    Top 10 BUY candidates that other tasks can reference by the label top_10.
  agent: stock_screener

technical_analysis:
  description: >
    Use stocks_owned tool to lookup existing holdings
    Use ticker_analytics_lookup tool to analyze technical signals and news summary for stocks_owned and top_10
    Identify stocks that should be sold from stocks_owned based on technical signals
  expected_output: >
    Top 5 SELL candidates based on technical signals for stocks in stocks_owned.
    Top 5 BUY candidates based on technical signals.
    Rationale for each BUY and SELL recommendation.
  agent: technical_analyst
  output_file: data/technical_report.txt

fundamental_analysis:
  description: >
    Use stocks_owned tool to lookup existing holdings.
    Use ticker_analytics_lookup tool to analyze fundamental signals and news summary for stocks_owned and top_10
    Identify stocks that should be sold from stocks_owned based on fundamental signals.
  expected_output: >
    Top 5 SELL candidates based on fundamental signals for stocks in stocks_owned.
    Top 5 BUY candidates based on fundamental signals.
    Rationale for each BUY and SELL recommendation.
  agent: fundamental_analyst
  output_file: data/fundamental_report.txt

portfolio_adjustments:
  description: >
    Use the stocks_owned tool to lookup existing holdings.
    Use the account_details tool to lookup the current portfolio value and cash position.
    Use the ticker_analytics_lookup tool to lookup the industry, sector, technical and fundamental signals.
    Make sure each holding is no more than 20% of the total portfolio value.
    Make sure there is industry/sector diversification.
    Recommend BUY and SELL adjustments.
  expected_output: >
    Breakdown of portfolio percentage by company.
    Breakdown of portfolio percantage by industry/sector.
    Breakdown BUY and SELL adjustments
  agent: portfolio_manager
  output_file: data/portfolio_report.txt

final_report:
  description: >
    Use the technical_report tool to lookup buy and sell candidates based on technical signals.
    Use the fundamental_report tool to lookup buy and sell candidates based on fundamental signals.
    Use the portfolio_report tool to lookup portfolio_report.
  expected_output: >
    A final report summary in markdown (without code blocks)
    Final report should have a BUY section with detailed rationale.
    Final report should have a SELL section with detailed rationale.
    Final report should have breakdown of portfolio percentage by company.
    Final report should have breakdown of portfolio percantage by industry/sector.
    Final report should have breakdown BUY and SELL adjustments.
  agent: report_analyst
  output_file: data/final_report.md

archive_report:
  description: >
    Archive the final report to elasticsearch using report_archive_tool.
  expected_output: >
    Response from the report_archive_tool or Exception if failed.
  agent: report_analyst